blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/direct_messages/create/JacksonChen666
    about: Directly to the owner. Not for issues or suggestions, but more of questions. Those can go to the discussion tab anyways.
